baseurl = "https://flhonker.github.io/"
DefaultContentLanguage = "en-us"
hasCJKLanguage = true
languageCode = "zh"
title = "Frank Liu"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true
googleAnalytics = "UA-123407007-1"

[Params]
hello = "Hi,I'm Frank"
subtitle = "Standing on the Shoulder of Giants."
logo = "https://res.cloudinary.com/flhonker/image/upload/flhonker-hugo/logo/frank1-Circle.jpg"
favicon = "https://res.cloudinary.com/flhonker/image/upload/flhonker-hugo/favicon/jetpacktocat.png"
share_img = "https://res.cloudinary.com/flhonker/image/upload/flhonker-hugo/share_img/happy.jpg"
dateFormat = "January 2, 2018"
commit = false
rss = true
baiduKey = "d82288793e5427ef06ad25f2ba778391"
#comments = false
#sharebutton = true
algolia = "fa0222a12d4979dee33b5ddd9b791436" # API key
#	APP ID = "AZMWPQSRYA"

#gcse = "012737790962522169780:fd1izxsfgrs" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
description = "Frank's Blog|Standing on the Shoulder of Giants.|frankliu624.me"
errorpage = "https://res.cloudinary.com/flhonker/image/upload/flhonker-hugo/404-not-found/404-Oops.jpg"

[[Params.bigimg]]
src = "https://res.cloudinary.com/flhonker/image/upload/flhonker-hugo/share_img/post-bg-linux_2.jpg"
desc = "I ❤️  #Linux - Jul 21,2018"

[[Params.bigimg]]
src = "https://res.cloudinary.com/flhonker/image/upload/flhonker-hugo/share_img/home-bg-google1.jpg"
desc = "Google AI is my dream. - Jun 30,2018"

#[[Params.bigimg]]
#src = "https://ws1.sinaimg.cn/large/00704eQkly1fs1gtlybnzj32ke0osu0z.jpg"
#desc = "KEUC - China Kubernetes End User Conference 2017"

[[Params.bigimg]]
src = "https://res.cloudinary.com/flhonker/image/upload/flhonker-hugo/share_img/post-bg-linux_4.jpg"
desc = "Linux serves all over the world. - Aug 28,2017"

#[[Params.bigimg]]
#src = "https://ws1.sinaimg.cn/large/00704eQkgy1fs1gv1sjguj31hc0u0qv6.jpg"
#desc = "Insight throught the Great Wall to the world"

[[Params.bigimg]]
src = "https://res.cloudinary.com/flhonker/image/upload/flhonker-hugo/share_img/post-bg-ubuntu1.jpg"
desc = "Ubuntu is my favorite."

[Author]
  name = "Frank Liu(flhonker)"
  website = "https://flhonker.github.io"
  email = "frankliu624@gmail.com"
  facebook = "FLHonker"
  #googleplus = "+jimmysong" # or xxxxxxxxxxxxxxxxxxxxx
  github = "flhonker"
  twitter = "FrankLi17399372"
  linkedin = "Frank Liu"
  #500px = "jimmysongio"
  #medium = "jimmysongio"
  #instagram = "jimmysongio"
  weibo = "西方以西的昂昂溪"

[[menu.main]]
    identifier = "Categories"
    name = "Categories"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "algorithm"
    url = "categories/algorithm"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "blockchain"
    url = "categories/blockchain"
    weight = 2

[[menu.main]]
    parent = "Categories"
    name = "Go"
    url = "categories/go"
    weight = 3

[[menu.main]]
    parent = "Categories"
    name = "opencv"
    url = "categories/opencv"
    weight = 4

[[menu.main]]
    parent = "Categories"
    name = "Linux"
    url = "categories/linux"
    weight = 5

[[menu.main]]
    parent = "Categories"
    name = "Career"
    url = "categories/career"
    weight = 6

[[menu.main]]
    parent = "Categories"
    name = "C++"
    url = "categories/c++"
    weight = 7

[[menu.main]]
    parent = "Categories"
    name = "Tags"
    url = "tags"
    weight = 8

[[menu.main]]
    identifier = "Gitbooks"
    name = "Gitbooks"
    weight = 2

[[menu.main]]
    parent = "Gitbooks"
    name = "OpenCV docs"
    url = "https://docs.opencv.org/"
    weight = 1

[[menu.main]]
    parent = "Gitbooks"
    name = "CentOS7扩展根分区操作手册"
    url = "posts/2018-04-26-centos7-linux扩展根分区"
    weight = 2

[[menu.main]]
    parent = "Gitbooks"
    name = "Hugo Handbook"
    url = "http://www.gohugo.org/doc/"
    weight = 3

[[menu.main]]
    parent = "Gitbooks"
    name = "Envoy proxy中文文档"
    url = "https://servicemesher.github.io/envoy"
    weight = 4

[[menu.main]]
    parent = "Gitbooks"
    name = "Linux命令基础"
    url = "posts/2018-04-27--linux-linux命令基础"
    weight = 5

[[menu.main]]
    identifier = "Publications"
    name = "Publications"
    weight = 3

[[menu.main]]
    parent = "Publications"
    name = "Cloud Native Go"
    url = "posts/cloud-native-go"
    weight = 1

[[menu.main]]
    parent = "Publications"
    name = "Cloud Native Python"
    url = "posts/cloud-native-python"
    weight = 2

[[menu.main]]
    parent = "Publications"
    name = "Cloud Native Java"
    url = "posts/cloud-native-java"
    weight = 3

[[menu.main]]
    identifier = "Projects"
    name = "Projects"
    weight = 4

[[menu.main]]
    parent = "Projects"
    name = "Cplus-engineer"
    url = "https://github.com/FLHonker/Cplus-engineer"
    weight = 1

[[menu.main]]
    parent = "Projects"
    name = "fl-bash"
    url = "https://github.com/FLHonker/fl-bash"
    weight = 2

[[menu.main]]
    parent = "Projects"
    name = "Cwheel"
    url = "posts/2018-07-01-c-c语言造轮子一"
    weight = 3

[[menu.main]]
    parent = "Projects"
    name = "go-BlockChain"
    url = "2018-07-03-blockchain-go打造区块链1"
    weight = 4

[[menu.main]]
    parent = "Projects"
    name = "E2E Tessting OCR"
    url = "posts/2018-07-27-career-e2e软件自动化测试中的ocr功能"
    weight = 5
    
[[menu.main]]
    parent = "Projects"
    name = "Frank's Hugo Blog"
    url = "https://github.com/FLHonker/flhonker-hugo"
    weight = 6

[[menu.main]]
    name = "About"
    url = "about"
    weight = 5
